name = "StirredReactor"
uuid = "0f306737-e494-4d62-9475-91bb092c0e67"
authors = ["Vinod Janardhanan"]
version = "0.1.0"

[compat]
julia = "1.8.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
